export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SET_EVENTS = 'SET_EVENTS';
export const EVENT_REGISTER_SUCCESS = 'EVENT_REGISTER_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
